# Generated by Django 4.2.16 on 2024-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('sign', models.CharField(blank=True, db_column='Sign', max_length=30, null=True)),
                ('item_class_id', models.BigIntegerField(blank=True, db_column='itemclassId', null=True)),
                ('barcode', models.CharField(blank=True, db_column='BarCode', max_length=30, null=True)),
                ('main_unit', models.CharField(blank=True, db_column='MainUnit', max_length=25, null=True)),
                ('sub_unit', models.CharField(blank=True, db_column='SubUnit', max_length=25, null=True)),
                ('small_unit', models.CharField(blank=True, db_column='SmallUnit', max_length=25, null=True)),
                ('main_unit_pack', models.FloatField(blank=True, db_column='MainUnitPack', null=True)),
                ('sub_unit_pack', models.FloatField(blank=True, db_column='SubUnitPack', null=True)),
                ('sale_tax_per', models.FloatField(blank=True, db_column='SaleTaxPer', null=True)),
                ('sell_price1', models.FloatField(blank=True, db_column='SellPrice1', null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemsClass',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('tree_index', models.CharField(blank=True, db_column='TreeIndex', max_length=500, null=True)),
                ('prev', models.CharField(blank=True, db_column='prev', max_length=100, null=True)),
                ('is_agent', models.BooleanField(blank=True, db_column='isAgent', null=True)),
            ],
            options={
                'db_table': 'ItemsClass',
            },
        ),
    ]
