# Generated by Django 4.2.16 on 2024-11-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileEndUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address_one', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_two', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_three', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_four', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_five', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_six', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_seven', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_eight', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_nine', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_ten', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'MobileEndUsers',
            },
        ),
    ]
